Generic python
Clinical-Genomics-Lund/qc_sentieon pull request #1
Opened 2024-08-15 14:26 UTC by ViktorHy

Another way of doing QC from sentieon. Happy to take some feedback

2024-08-16 09:02 UTC, alkc requested changes
Streamlined a bit of the code (hope it still works >_>). Removed unused imports. Added other comments!

2024-08-16 09:02 UTC, alkc commented on qcify.py
> +        "version" : "null",
```suggestion
        "version" : None,
```

2024-08-16 09:02 UTC, alkc commented on qcify.py
> +        cov_dict['coverage_uniformity'] = "null"
```suggestion
        cov_dict['coverage_uniformity'] = None
```

`None` is easier to test for down the line, compared to `"null"`, which is a "truthy" non-empty string.

2024-08-16 09:02 UTC, alkc commented on qcify.py
> +    return algo_dict
```suggestion
    with open(filename, 'r') as file:       
        for line in file:         
            line = line.strip()        
            if line.startswith('#'):
                # The next line after the one starting with '#' contains the header
                headers_line = next(file).strip().split('\t')
                continue
                
            if headers:
                data = line.split("\t")
                break
                
            if headers is None or data is None:
                raise ValueError("File does not contain expected headers and data lines.")               
        
    picard_dict = dict(zip(headers_line, data_line))
    algo_dict = {
        "software" : category,
        "version" : None,
        "result": picard_dict
    }
    return algo_dict
```

2024-08-16 09:02 UTC, alkc commented on qcify.py
> +    return algo_dict
```suggestion
def read_vertical_picard(filename, category):
    """
    Read rowbased data from picard and store as dict per column
    Histogram-data for plotting?
    """
    
    data = defaultdict(list)
    
    with open(filename, 'r') as file:
        for line in file:    
            if not line.startswith('#'):
                header_line = line.strip().split()
                break

        for line in file:
            line = line.strip()
            if not line:
                continue
                
            values = line.split()
            
            # Map each value to its corresponding header
            for i, var_name in enumerate(header_line):
            
                # Append the value to the appropriate list in the dictionary
                # Automatically convert to int or float if possible, otherwise keep as string
                
                value = values[i]
            
                for conversion in (int, float):
                    try:
                        value = conversion(value)
                        break
                    except ValueError:
                        continue
                
                data[var_name].append(value)
                
    algo_dict = {
        "software" : category,
        "version" : None,
        "result": data
    }
    return algo_dict              
```

2024-08-16 09:02 UTC, alkc commented on qcify.py
> +#!/data/bnf/sw/miniconda3/bin/python
Are you sure about this shebang? Will this work on hopper?

2024-08-16 09:02 UTC, alkc commented on qcify.py
> +from pprint import pprint
```suggestion
from collections import defaultdict
```

`defaultdict` is used for a suggested rewrite below

`pprint` is not actually used in the script

2024-08-16 09:02 UTC, alkc commented on qcify.py
> +        "version" : "null",
Regular `None` is easier to handle later on in python/CDM

2024-08-16 09:02 UTC, alkc commented on qcify.py
> +        "version" : "null",
```suggestion
        "version" : None,
```

See comment above

2024-08-16 09:02 UTC, alkc commented on qcify.py
> +    return algo_dict
```suggestion
def coverage_calc(filename,category):
    """
    Accepts CoverageMetrics summary from sentieon.
    Return coverage-thresholds at set values and coverage uniformity (IQR/MEDIAN) calcs
    """
    with open(filename, 'r') as file:
        lines = file.readlines()
    
    headers_line = lines[0].strip().split('\t')
    sample_line = lines[1].strip().split('\t')
        
    cov_dict = dict(zip(headers_line, sample_line))
    # coverage uniformity
    # interquartile range of coverage, if Q1 and Q3 are valid integers
    try:
       q1 = int(cov_dict['granular_Q1'])
       q3 = int(cov_dict['granular_Q3'])
       median = int(cov_dict['granular_median'])
    except (ValueError, KeyError):
        q1, q3, median = None, None, None
        
    if q1 is not None and q3 is not None and median not in (None, 0):
        iqr = q3 - q1
        cov_dict['coverage_uniformity'] = iqr / median
    else:
        cov_dict['coverage_uniformity'] = None
        
       
    algo_dict = {
        "software" : category,
        "version" : None,
        "result": cov_dict
    }
    return algo_dict
```
```suggestion
def coverage_calc(filename,category):
    """
    Accepts CoverageMetrics summary from sentieon.
    Return coverage-thresholds at set values and coverage uniformity (IQR/MEDIAN) calcs
    """
    with open(filename, 'r') as file:
        lines = file.readlines()
        headers_line = lines[0].strip().split('\t')
        sample_line = lines[1].strip().split('\t')
    cov_dict = dict(zip(headers_line, sample_line))
    # coverage uniformity
    # interquartile range of coverage, if Q1 and Q3 are valid integers
    if isinstance( cov_dict["granular_Q1"], int) and isinstance(cov_dict['granular_Q3'], int):
        iqr = (int(cov_dict['granular_Q3']) - int(cov_dict['granular_Q1']))
        cov_dict['coverage_uniformity'] = iqr / int(cov_dict['granular_median'])
    else:
        cov_dict['coverage_uniformity'] = "null"
    algo_dict = {
        "software" : category,
        "version" : "null",
        "result": cov_dict
    }
    return algo_dict
```

2024-08-16 09:02 UTC, alkc commented on qcify.py
> +    parser.add_argument("-s", "--SID",            help="Sample ID, required")
This arg is only used to set the output file-name. Why not just `-o, --output_name` instead, or dump json to stdout and pipe to `$sample_id.json` in the nextflow process?

2024-08-16 09:48 UTC, ViktorHy commented on qcify.py
> +        cov_dict['coverage_uniformity'] = "null"
yeah I forgot the name for null in python, so I blanked :P

2024-08-16 09:49 UTC, ViktorHy commented on qcify.py
> +#!/data/bnf/sw/miniconda3/bin/python
nope it wont

2024-08-16 09:51 UTC, ViktorHy commented on qcify.py
> +    parser.add_argument("-s", "--SID",            help="Sample ID, required")
yeah makes sense.

2024-08-19 07:56 UTC, ViktorHy commented
Made most of suggested changes, thanks! Care to take another look?

2024-08-19 08:30 UTC, alkc approved these changes
Changes look good. Haven't tested functionality though!

2024-08-19 08:35 UTC, merged